version: "3"
services:
  app:
    container_name: app
    restart: always
    command: yarn start --env=production
    env_file:
      - .env
    build: ./server
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "3000:3000"
      - "5432"

  mqttclient:
    container_name: mqttclient
    restart: always
    command: yarn start --env=production
    env_file:
      - .env
    build: ./mqttClient
    depends_on:
      - mqtt
    links:
      - mqtt
    ports:
      - "5000:5000"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: gegeraptor
      POSTGRES_USER: gegeraptor
      POSTGRES_DB: graphql-node
    # volumes:
    #   - ~/dbdata:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /opt/conf/mqtt/data:/mosquitto/data
      - /opt/conf/mqtt/log:/mosquitto/log
