version: "3"
services:
  app:
    container_name: app
    command: yarn start
    env_file:
      - .env
    build: ./server
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "3000:3000"
      - "5432"

  test:
    container_name: test
    command: sh -c "sleep 9 && yarn test"
    env_file:
      - .env
    build: ./server
    depends_on:
      - app
    links:
      - app


  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: gegeraptor
      POSTGRES_USER: gegeraptor
      POSTGRES_DB: graphql_node
    # volumes:
    #   - ~/dbdata:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /opt/conf/mqtt/data:/mosquitto/data
      - /opt/conf/mqtt/log:/mosquitto/log
